# Generated by Django 3.2 on 2024-10-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombreo',
            new_name='nombre',
        ),
    ]
